#+startup: indent
#+options: toc:nil  ':t num:3 H:3
#+OPTIONS: tags:nil
#+author: Luke M Perez
#+date: Summer 2016
#+title: Outline International Relations


* General Concepts
** Levels of Analysis
1. Individual Level
   1. Human Behavior
      1. Classical IR (Carr, Morgenthau, Neibuhr) focused on "human
         nature" as /the/ cause of war. Rejected as reductionist by
         Waltz and structural theorists.
      2. Structuralism's strength from 1980ff waning in light of
         evolutionary psychology, GT, constructivism
      3. Renewed interest of individual levels and their interaction
         with state and system suggests potential for dynamic models
         of IR (IPE, systems theory, etc.) ::need citation:: 
   2. Human Nature
   3. Criticisms
      1. Arguments of human nature (cf. Morgenthau, Neibuhr) are
         reductionist
      2. Individuals are not the essential actors in IR
2. State Level
   1. Domestic politics pushing upward into the system
   2. Examples included
      1. Open Economy Politics
      2. Neoclassical realism
   
3. System Level
   1. Anarchy is a material variable, creates incentives and
      constraints on state behavior
   2. Criticisms
      1. Waltz relies on theoretical reductionism, treating the state
         as a microeconomic firm. 
** Agent-Structure Problem
1. Who influences who, /agents on structure/ or /structures on agents/?
2. Rationalists emphasize the agents as those who make the system and institutions
   1. Wagner (2010) suggests the international system is the product
      of international bargains between states
   2. Milner (199?) raises the possibility that it could be
      /rationalism all the way down/ such that important concepts,
      like sovereignty, thought to be firm are much more malleable.
3. Constructivists stress the constitutive ontology of agents and structures
   1. Agents and structure emerge together
   2. Structure shapes agents in ways that are largely imperceptible.
      1. Wendt (1999) on the culture's of anarchy: Hobbesian, Lockean, Kantian
      2. Ruggie (1992): Embedded liberalism thesis. Logic of
         free-market, global capitalism baked into the system by the
         framers of post-war order.          
** Principle-Agent Model
** Strategic models
*** Interests vs. Preferences
1. Not identical
   1. Preferences are /what/ individual actors want.
   2. Interests are /why/ they want.
2. Norms, morality, or interest may drive interests (Wagner 2010;
   Frieden 1999 [Lake and Powell])
   1. preferences and the conflict between them are what drive strategy.
   2. NB: Hobbes on the causes of war: competition, diffidence, glory
      /vs/ Thucydides' fear, pride, interest.
** Institutions
*** Rationalists Definitions
1. International regimes
   1. Laws of War
   2. International Organizations
2. Institutions as human made constraints and economic models
   1. "Institutions are the humanly devised constraints that structure
      political, economic and social interaction. They consist of both
      informal constraints... and formal rules. ... Together with the
      standard constraints of economics they define the choice set and
      therefore determine transaction and production costs and hence
      the profitability and feasibility of engaging in economic
      activity" (North 1991).
3. Actors (states, non-states) behave in predictable patterns and seek
   utility maximizing strategies for any given strategy space (Lake
   and Powell 1999). 


*** Normative Definitions
1. The rules and patterns of behavior Keohane (1987).
2. Cultures of anarchy and norm dynamics
   1. Multiple "cultures" of enmity, competition, friendship that form
      a path dependency between any two (or groups) of nations (Wendt 1999)
   2. Change within and between cultures depends on entrepreneurs who
      bring about change in state behavior, ultimately changing the
      path dependency of relationships between actors (Finnemore and Sikkink).
3. 
** Cooperation 
*** Cooperation /vs/ Anarchy
1. Anarchy frustrates cooperation because states are preoccupied with
   security (Waltz, Mearshimer, etc.)
2. Anarchy /predicts/ cooperation because self-help suggests
   outsourcing what cannot be accomplished internally (Keohane, etc.)
3. Anarchy is called into question because cooperation suggests
   hierarchy and order and not Hobbesian system. 
*** Cooperation and state behavior
1. Harmony and Discord require no change in behavior on the part of actors.
2. Cooperation is /contingent/ change in behavior interdependent on
   the actions of other partners in the deal.

* War and conflict
** Why War?
*** Misreading of capabilities
1. War is often welcomed by states who believe it will be quick, and
   victory assured (Blainey 1988)
   1. Often by both sized
   2. Often against evidence to the contrary
*** The inefficiency puzzle (Fearon 1995)
1. Given that war always exerts some cost on states such that a bargain /ex ante/
   would be lest costly, why do states choose war?
2. Three reasons are posited
   1. Uncertainty and misrepresenting private information
   2. States cannot solve the commitment problems
   3. Issue indivisibility
3. Suggests, however, that no such factors exist which would predict
   war over other factors. /war is the error term/ (Gartzke 1999).
* International Political Economy
** OEP
*** Method and approach
*** Key findings
*** Criticisms
**** Oatley 2011. 
Methodological reductionism produces inaccurate knowledge. Most OEP
seems to drop the final step (model the system with necessary) by
assuming rather than showing that the system does not have an effect. 
* International Organization

* Foreign Policy
** History vs Social Science
1. Three major differences between IR and Diplomatic History (Dip-hist)
   1. Chronology (history) vs Causal mechanisms (IR)
   2. Individual events (history) vs Comparative cases (IR)
   3. Morality: history more comfortable, IR emphasizes facts over values
2. IR can, and should, draw from history as it builds theories and
   hypotheses without falling into an inductive-qualitative trap.
** Small group dynamics



* Annotated Readings
** Blainey, Geoffrey, (1988) [GB88]
Blainey's /The Causes of War/ surveys every major war from 1700 to
roughly 1970, showing how much of the conventional wisdom about the
causes of war are misguided or outright false. War occurs because of
power imbalances and misperceptions about any given nation's position
in the world. Although Blainey lacks the rigor of formal or empirical
models, his findings approach conclusions found by political
scientists: that war is bargaining problem of sorts, a part of the
political process between nations. One notable line of inquiry is his
study of the Manchester creed of the late-19th and early-20th
century. Cooperation in this period was at least as deep and broad as
modern globalization, then as now, the conventional wisdom was that
economics and cultural openness were making war obsolete. But then, as
now, politics rather than economics proves to be sovereign.  
** Bennett, Andrew (2013) [Bennett2013]
** Broaumoeller, Bear F. (2012) [Broemoeller2012]
** de Marchi, Scott (deMarchi2005)
Examines the limitations of quantitative and and formal models in
political science, arguing that computational models can compliment
and improve traditional empirical and formal research designs.
Following Achen (2002), de Marchi argues that empirical modeling too
often includes an over abundance of variables, thereby overfitting
their model and producing spurious findings (p. 11). Formal theorists
are not immune to this problem because an abundance of logically
consistent models exist that can be fitted to the empirical
observations such that whatever the researcher wishes to show, /a
priori/ can usually be shown. Computation models, however, can
adjudicate between various models by allowing researchers to test a
model against a closer approximation of the Data Generating Process
(DGP) before doing so on the actual empirical data. This approach,
along with /out-of-sample/ (OOS) testing helps researchers avoid the
pitfalls of overfitting or underfitting their models.   
** Keohane, Robert O. 1988
Survey of two emerging approaches to the study of international
institutions, rationalist and constructivist. Rationalist approaches
rely on game theory and neoclassical economic theory to develop models
of utility maximizing strategies. Rationalist approaches assume actors
are self-aware they are in institutions---often even self-conscious
that they constructed the institutions that constrain
themselves. Institutions, in this view, rely on /exchange theory/
positing that (a) there are gains to be made from cooperation but (b)
cooperation is costly: thus, institutions help manage those
costs. Constructivist approaches, conversely, point out that actors
are often unaware they are acting under the constraints of the
institution and that institutions contain and promote /norms/ as the
primary constraint mechanism on actors. 
** Oatley, Thomas (2012) [TO12reduct]
Oatley critiques the methodological reductionism of OEP because it
risks producing false or inaccurate knowledge. According to Oatley,
OEP assumes---rather than shows---that the system under study can be
studied without consideration of system level effects. In at least
three issue areas he shows that modeling the system level effects
produces different findings from a strict OEP method that only models
domestic level variables. 
** Wagner, R. Harrison 1986
Using noncooperative game theory, Wagner models balancing theory in
systems between 3--5 states. He shows that a core 'realist' (scare
quotes original) assumptions like exogenous change in
preferences---i.e., no state can be sure another's preferences will
not change tomorrow---uncertainty, and the possibility of conflict can
lead to stability within a given system. Stability, however, is
defined as the non-death of states; that is, war and conflict can
occur, but the system is considered stable if all states
remain. Peace, in contrast, is defined as the absence of war. Although
it is possible for there to be stability without peace, Wagner is
silent on the possibility of peace without stability. 
** Waltz, Kenneth N. 1959 
/Man, the State, and War/ from Waltz's dissertation, examines the
levels of analysis (individual, state, system) and the causes of war
and peace among nations. 
** Waltz, Kennith N. 1979 
/Theory of Internat'l Politics/ lays the foundation for nearly
all contemporary IR research either by critiquing, extending, or
modifying Waltz's basic definitions of theory, reductionist/systemic
approaches, and philosophy of social science. Waltz's microeconomic
method and systemic approach recast classical realism into it's
neorealist, or structural, formulation found in Mearshimer and
others. Waltz stresses the material forces of the international system
because he finds the analysis produced by first-image or second-image
approaches wanting. The goal of any theory is /parsimony/; systemic
theory building allows him to derive elegant "theories" about
international politics when states are treated like firms in
microeconomic theory. Statistics, for example, "are simply description
in numberical form" (p. 3). What matters is not the quantitative (or
formal) model and evidence, but the theory building. However
influential /Theory of International Politics/ proved to be, his
prescriptions were not uniformly received. Neoclassical-Realism and
Open Economy Politics, for example, marked a turn toward second-image
analysis and attempt to look at variables within states as causes for
international political phenomenon. 
